### ISSUE TITLE
Error when parsing source array.

### ISSUE THREAD

**Issue by twhughes** [wsshin/maxwellfdfd#1]
When giving maxwell_run 'SRCJ' an array of source objects, I recieve this error:

Incorrect number of right hand side elements in dot name assignment.  Missing [] around left hand side is a likely cause.

changing line 49 from 

            this.gt = gt
to

            if (length(this) == 1)
                this.gt = gt;
            else
                for i = (1:length(this))
                    this(i).gt = gt;
                end
            end
		end

seems to fix the issue temporarily

**Comment by wsshin** [comment]
Hi Tyler,

I cannot reproduce this problem myself.  Could you send me a minimum example that generates this problem?

Wonseok

**Comment by twhughes** [comment]
Try this script.  It is possible that this issue is due to me not understanding the primal / dual grid constraints.

[PhaseShiftedSource.m.gz](https://github.com/wsshin/maxwellfdfd/files/78971/PhaseShiftedSource.m.gz)

**Comment by twhughes** [comment]
Could you also send me your working example of correctly using an array of source objects in maxwell_run()?  This may help me understand what is going wrong here.  

At least in my copy, (which is older) It seems like more of a syntax error with function set_gridtype(this, gt) in Source.m not being set up to set the grid type for each source array element.

**Comment by wsshin** [comment]
It turns out that this is a combination of two problems.

1.  It turns out that there was actually a problem in handling an array of Source instances.  I have fixed it and pushed the change to GitHub.  You can also fix it yourself by changing

                src = arg;
                src.set_gridtype(ge);
                srcj_array = [srcj_array(1:end), src];

to

                srcj_array_curr = arg;
                for src = srcj_array_curr
                    src.set_gridtype(ge);
                end
                srcj_array = [srcj_array(1:end), srcj_array_curr];

and also

                src = arg;
                src.set_gridtype(alter(ge));
                srcm_array = [srcm_array(1:end), src];

to

                srcm_array_curr = arg;
                for src = srcm_array_curr
                    src.set_gridtype(alter(ge));
                end
                srcm_array = [srcm_array(1:end), srcm_array_curr];

2.  After you fix this bug, now you get another error message about x-grid generation.  This is due to the wrong location of the sources as you suspected.
You can easily fix this problem by shifting the source distribution slightly.  For example, you can change 
	z = X/2 - 1
to
	z = X/2 - 0.5
in your script.  

The reason this solves the problem is as follows.  The x-polarized point sources should be located at the midpoints of x edges of the Yee grid cells.  Therefore, while constructing the point sources by iterating i over -z:1:z, MaxwellFDFD tries to generate a grid such that -z:1:z are located at the midpoints of the grid cells.  

Note that as a result MaxwellFDFD attempts to put x = ±L at the midpoints of the grid cells.  However, your Box([-L, L; -L, L; 0, 1], [dl,dl, 1]) tries to put x = ±L at the end points of grid cells.  These two constraints conflict, so the x-grid construction fails.

By making sure that the x-locations of your x-polarized points sources to be different from x = ±L, you can successfully create the grid.

Hope this helps!

Wonseok

**Comment by twhughes** [comment]
Thanks for looking into this issue and for the instructive response about the grid generation issue.  I was quite confused about it before but I believe this clears up the issues I was having with it.  

Thanks again!

Tyler
